package year2025

import kotlin.test.Test
import kotlin.test.assertEquals

class Day07Test {

    companion object {
        private val INPUT = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent()
    }

    private val day = Day07()

    @Test
    fun part1() {
        assertEquals(21, day.part1(INPUT))
    }

    @Test
    fun part2() {
        assertEquals(40, day.part2(INPUT))
    }
}
